# Generated by Django 4.1.3 on 2023-01-01 12:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_teacher_account'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curses',
            new_name='Course',
        ),
        migrations.AddField(
            model_name='teacher',
            name='request_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
