# Generated by Django 4.1.3 on 2023-01-02 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_alter_teacher_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'دوره', 'verbose_name_plural': 'دوره ها'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'مدرس', 'verbose_name_plural': 'مدرسان'},
        ),
        migrations.AlterField(
            model_name='course',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(max_length=256, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=64, verbose_name='اسم دوره'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start',
            field=models.DateField(verbose_name='تاریخ شروع دوره'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher', verbose_name='استاد دوره'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL, verbose_name='حساب کاربری استاد'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال بودن'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='request_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درخواست'),
        ),
    ]
