# Generated by Django 4.1.3 on 2023-01-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_course_options_alter_teacher_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='اسم دوره'),
        ),
    ]
