# Generated by Django 4.1.3 on 2023-01-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(default='ss', upload_to='course', verbose_name='تصویر'),
            preserve_default=False,
        ),
    ]
