# Generated by Django 4.1.3 on 2023-01-03 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0008_course_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatisfactionـSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bad', models.ManyToManyField(related_name='poll_bad', to=settings.AUTH_USER_MODEL)),
                ('good', models.ManyToManyField(related_name='poll_good', to=settings.AUTH_USER_MODEL)),
                ('mid', models.ManyToManyField(related_name='poll_mid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.satisfactionـsurvey'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.satisfactionـsurvey'),
        ),
    ]
