# Generated by Django 4.1.3 on 2023-01-03 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_satisfactionـsurvey_course_poll_teacher_poll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='poll',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.satisfactionـsurvey'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='poll',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.satisfactionـsurvey'),
        ),
    ]
