# Generated by Django 4.1.3 on 2023-01-03 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0010_alter_course_poll_alter_teacher_poll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satisfactionـsurvey',
            name='bad',
            field=models.ManyToManyField(blank=True, related_name='poll_bad', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='satisfactionـsurvey',
            name='good',
            field=models.ManyToManyField(blank=True, related_name='poll_good', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='satisfactionـsurvey',
            name='mid',
            field=models.ManyToManyField(blank=True, related_name='poll_mid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='poll',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.satisfactionـsurvey'),
            preserve_default=False,
        ),
    ]
