# Generated by Django 4.1.3 on 2023-01-03 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_satisfactionـsurvey_bad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('choices', models.ManyToManyField(related_name='poll', to='accounts.choice')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='poll',
        ),
        migrations.DeleteModel(
            name='SatisfactionـSurvey',
        ),
        migrations.AddField(
            model_name='poll',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='accounts.teacher'),
        ),
    ]
