# Generated by Django 4.1.3 on 2023-01-03 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='for_course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='accounts.course'),
            preserve_default=False,
        ),
    ]
