# Generated by Django 4.1.3 on 2022-12-31 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_jozveh_alter_article_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jozveh',
            new_name='Handout',
        ),
    ]
