# Generated by Django 4.1.3 on 2023-01-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_jozveh_handout'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='handout',
            options={'verbose_name': 'جزوه', 'verbose_name_plural': 'جزوات'},
        ),
        migrations.AlterField(
            model_name='handout',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='handout',
            name='pdf',
            field=models.FileField(upload_to='pdf', verbose_name='فایل پی دی اف'),
        ),
        migrations.AlterField(
            model_name='handout',
            name='title',
            field=models.CharField(max_length=64, verbose_name='عنوان'),
        ),
    ]
