# Generated by Django 4.1.3 on 2023-01-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_handout_options_alter_handout_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=64, unique=True, verbose_name='عنوان'),
        ),
    ]
